### ISSUE TITLE
problem building on OpenBSD

### ISSUE THREAD

**Issue by Megatokio** [Megatokio/Libraries#7]
Hi kio,

Thanks so much for your great program zasm! I've used it and compiled
it on Linux and really think it's an awesome program. I tried to
compile zasm on OpenBSD using both clang and gcc and ran into some
errors, I've attached the logs for reference. I'd love to be able to
help port zasm, but my unix programming is still a bit weak. Please
let me know if I can help.

-Asad

**Comment by Megatokio** [comment]
durationstr(time_t):
i fixed the problem with varying size of time_t and long vs. int64 probably and pushed it to branch "test". 
please checkout branch "test" and tell me whether it works for you.

**Comment by Megatokio** [comment]
static FD stdin:
stdin etc. seem to be a #define on your platform. I'll see how to fix this best.

**Comment by lodhia** [comment]
Thanks a lot! 

I'm compiling on a ARMv8 architecture, I think it may be big endian, but I'm not sure (I tried looking it up, but docs say they can run in either mode).

I just cloned 'test' branch of Libraries and 'master' branch of zasm. When I compiled this time only the following errors were left
**In file included from Libraries/cstrings/cstrings.cpp:23:
In file included from Libraries/Templates/Array.h:23:
Libraries/unix/FD.h:69:12: error: '__sF' declared as array of references of type 'FD (&)'
        static  FD      stdin;
                        ^
/usr/include/stdio.h:197:21: note: expanded from macro 'stdin'
#define stdin   (&__sF[0])
                      ^
In file included from Libraries/cstrings/cstrings.cpp:23:
In file included from Libraries/Templates/Array.h:23:
Libraries/unix/FD.h:70:12: error: '__sF' declared as array of references of type 'FD (&)'
        static  FD      stdout;
                        ^
/usr/include/stdio.h:198:22: note: expanded from macro 'stdout'
#define stdout  (&__sF[1])
                      ^
In file included from Libraries/cstrings/cstrings.cpp:23:
In file included from Libraries/Templates/Array.h:23:
Libraries/unix/FD.h:71:12: error: '__sF' declared as array of references of type 'FD (&)'
        static  FD      stderr;
                        ^
/usr/include/stdio.h:199:22: note: expanded from macro 'stderr'
#define stderr  (&__sF[2])
                      ^
3 errors generated.
gmake: *** [Makefile:67: tmp/cstrings.o] Error 1**

when I changed in FD.h, FD.cpp  stdin, stdout and stderr to _stdin _stderr as you suggested I obtained
**Libraries/unix/files.cpp:992:2: error: unknown type name 'DIR'
        DIR* dir = opendir(dpath);
        ^
Libraries/unix/files.cpp:992:13: error: use of undeclared identifier 'opendir'
        DIR* dir = opendir(dpath);
                   ^
Libraries/unix/files.cpp:1096:2: error: unknown type name 'DIR'
        DIR* dir = opendir(path);                                       // note: sets sporadic errors
        ^
Libraries/unix/files.cpp:1096:13: error: use of undeclared identifier 'opendir'
        DIR* dir = opendir(path);                                       // note: sets sporadic errors
                   ^
Libraries/unix/files.cpp:1233:48: error: use of undeclared identifier 'lchmod'
        err = deref_last_symlink ? chmod(path,mode) : lchmod(path,mode);
                                                      ^
Libraries/unix/files.cpp:1331:22: error: no member named 'f_type' in 'statfs'
        this->fstype            = fs.f_type;
                                  ~~ ^
6 errors generated.
gmake: *** [Makefile:79: tmp/files.o] Error 1**

which is odd, since dirent.h is included I think?

**Comment by Megatokio** [comment]
ARMv8 can both and normally they use Little Endian because that results in less endianess problems when people did not care about endianess in their code. You can look at Libraries/kio/detect_configuration.h whether endianess is correctly deetcted.

stdin etc: sorry, my fault. i didn't push this commit :-/
please checkout branch "test" and try again.

DIR: this is defined in <dirent.h> on Linux, on BSD there is <sys/dirent.h> which is included by your compiler, and as it does not complain it is present. 
The OpenBSD manpage says #include <dirent.h> plus #include <sys/types.h>. Does this work?

lchmod: it seems OpenBSD also has no lchmod(). i'll change the #ifdef in line 1204 to include OpenBSD too.

fs.f_type: seems to be not present in OpenBSD. i'll add an #ifndef

**Comment by lodhia** [comment]
Thanks Kio!

I pulled test again and compiled and got the old error again regarding DIR. When I added a line at 34 in files.cpp saying #include <dirent.h> compilation went through successfully.

**Comment by Megatokio** [comment]
i pushed the final fix to "test". can you checkout and verify it's working before i merge it into 'master'?
i have force pushed so you should 'reset' your local branch to this state.
thanks for your work! :-)

**Comment by lodhia** [comment]
No worries, thank you for this awesome program. I just removed old directories of zasm and Libraries and pulled the latest zasm and the test branch of Libraries and was able to successfully compile.

**Comment by Megatokio** [comment]
thanks again. :-) 
merged and closed. :-)
